export interface HurricaneTrack {
  title: string;
  file: string;
  note?: string;
}

export const hurricaneTracks: HurricaneTrack[] = [
  { title: "Tailgaitin'", file: "1. Tailgaitin'.mp3" },
  { title: "Tiger Mighty Tiger", file: "2. Tiger Mighty Tiger.mp3" },
  { title: "Some Kinda Wonderful", file: "3. Some Kinda Wonderful.mp3" },
  { title: "The Tigers Just Can't Be Beat", file: "4. The Tigers Just Can't Be Beat.mp3" },
  { title: "Lord I Was Born A Clemson Fan", file: "5. Lord I Was Born A Clemson Fan.mp3" },
  { title: "Celebrate (Florida State)", file: "6. Celebrate_FlaState.mp3" },
  { title: "No Knocks On Woody Dantzler", file: "7. No Knocks On Woody Dantzler.mp3" },
  { title: "Rock This Town", file: "8. Rock This Town.mp3" },
  { title: "Nothin' But A Bulldog", file: "9. Nothin' But A Bulldog.mp3" },
  { title: "One Man Band", file: "10. One Man Band.mp3" },
  { title: "Piece Of The Rock", file: "11. Piece Of The Rock.mp3" },
  { title: "Louie Louie", file: "12. Louie Louie.mp3" },
  { title: "Against The Tigers They Can't Score", file: "13. Against the Tigers They Can't Score.mp3" },
  { title: "Beat North Carolina", file: "14. Beat North Carolina.mp3" },
  { title: "Devil With The Blue Dress On", file: "15. Devil With the Blue Dress On.mp3" },
  { title: "Ain't No Mountain High", file: "16. Ain't No Mountain High(W.Bradley).mp3", note: "feat. W. Bradley" },
  { title: "Are You Ready For Some Football", file: "17. Are You Ready For Some Football.mp3" },
  { title: "Running Down The Hill", file: "18. Running Down The Hill.mp3" },
  { title: "Saturday Night's Alright", file: "19. Saturday Night's Alright.mp3" },
  { title: "Clemson Tiger Girls", file: "20. Clemson Tiger Girls.mp3" },
  { title: "Tiger (Fire)", file: "21. Tiger (Fire).mp3" },
  { title: "Walking In Clemson", file: "22. Walking In Clemson.mp3" },
  { title: "Shoulda' Coulda' Woulda' Song", file: "23. Shoulda' Coulda' Woulda' Song.mp3" },
  { title: "The Tigers Are Back In Town", file: "24. The Tigers Are Back in Town.mp3" },
  { title: "Football Wizard", file: "25. FootBall Wizzard.mp3" },
  { title: "I Hate Florida State", file: "26. I Hate Florida State.mp3" },
  { title: "0 & 11 (The Perfect Season)", file: "27. 0 & 11 (The Perfect Season).mp3" },
  { title: "Duke Blue Devil Fan", file: "28. Duke Blue Devil Fan.mp3" },
  { title: "Let's Beat Alabama (Natty Mix)", file: "29. Let's Beat Alabama _NattyMix.mp3" },
  { title: "I Am A Clemson Fan", file: "30. I Am A Clemson Fan.mp3" },
  { title: "Saturday In The Park", file: "31. Saturday In The Park.mp3" },
  { title: "When The Valley's 'a Rockin'", file: "32. When The Valley's 'a Rockin'.mp3" },
  { title: "Linda Lou", file: "33. Linda Lou.mp3" },
  { title: "Rally In The Valley", file: "34. Rally In The Valley.mp3" },
  { title: "I Know A Little", file: "35. I Know a Little.mp3" },
  { title: "The Heat Is On", file: "36. The Heat Is On.mp3" },
  { title: "Tiger Tails To You", file: "37. Tiger Tails To You.mp3" },
  { title: "Chickens Just Don't Understand", file: "39. Chickens Just Don't Understand(B.Walters).mp3", note: "feat. B. Walters" },
  { title: "Clemson Tiger Fans", file: "40. Clemson Tiger Fans.mp3" },
  { title: "Beat South Carolina", file: "41. Beat South Carolina.mp3" },
  { title: "Papa Was A Seminole", file: "42. Papa was A Seminole(W.Bradley).mp3", note: "feat. W. Bradley" },
  { title: "Papa's Got A Brand New Bag", file: "43. Papa's Got A Brand New Bag.mp3" },
  { title: "Soul Man (J. Phillips Tribute)", file: "44. Soul Man_JPhillips Tribute.mp3" },
  { title: "Sympathy For The Curse", file: "45. Sympathy for The Curse.mp3" },
  { title: "Takin' Care Of Business", file: "46. Takin' Care of Business.mp3" },
  { title: "America", file: "47. America.mp3" },
  { title: "Tiger Tails (Duke '02) w/ Tiger Rag", file: "48. Tiger Tails (Duke'02)w_Tiger_Rag.mp3" },
  { title: "We Can Make It Work", file: "49. We Can Make It Work.mp3" },
  { title: "You Get What You Get", file: "50. You Get What You Get.mp3" },
  { title: "Very Superstitious", file: "51. Very Superstitious.mp3" },
  { title: "The Way It Is (Live)", file: "52. The Way It Is _Live_.mp3" },
];
